
[package]
name = "shelby"
version = "0.1.0"
edition = "2021"

[dependencies]
shelby_backend = { path = "shelby_backend" }
rocket = { version = "0.5", features = ["json", "secrets"] }
paste = "1.0"

[workspace]
members = ["shelby_backend"]
