name: Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag name
        id: prep
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF##*/})"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: christopher22/shelby:${{ steps.prep.outputs.tag }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          file: ./Dockerfile

      - name: Logout from DockerHub
        if: always()
        run: docker logout