name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Rust and caching
        uses: moonrepo/setup-rust@v1
      - name: Run all tests
        run: cargo test --all --nocapture